### ISSUE TITLE
revc::api::frame::Aligned::default unsoundly creates uninitalised values of arbitrary type

### ISSUE THREAD

**Issue by ghost** [revcx/revc#21]
Sample code:

```rust
fn main() {
    let value: &&u32 = revc::api::frame::Aligned::<&&u32>::default().data;
    dbg!(**value);
}
```

This crashes on my machine with a segfault.

I needed to load the library from git in order to cause this, looks like this function didn't exist on 0.2.0 which is the latest release I see from crates.io

**Comment by rainliu** [comment]
it is on purpose to create uninitalised value for frame::Aligned data structure, mainly for frame data.

you can search how it is used in the code.
